### ISSUE TITLE
Why is this package not registered?

### ISSUE THREAD

**Issue by freemin7** [dalum/Gloria.jl#4]
I found your package interesting and would be curios whether you want look into registering it.

**Comment by dalum** [comment]
Hi! And thanks for showing interest! :blush: 

I didn't register it because I didn't think it was mature enough to have any use to others, and I personally didn't have time to really maintain it consistently.  But seeing that a few people have shown interest in the package now, it might be worth considering.

**Comment by freemin7** [comment]
Well i am not tied deeply to your package, i could switch to another binding and i wouldn't be able to maintain it either.

**Comment by dalum** [comment]
Registration process in progress. :tada:
